### PR TITLE
Polymer v1 update

### PR DESCRIPTION
**Pull request by Granze**
This PR is just a quick update to let the loader work with Polymer v1.

### CODE REVIEW

**Comment by sarendipitee** [comment]
Looks good to me. I'm not at my laptop right now, ping me in a day or so if I haven't updated this on NPM yet.

**Comment by Granze** [comment]
ok, thanks!

**Comment by webberig** [comment]
ping ? :-)
I'm about to start experimenting with polymer, so it would be great if I could try out this loader supporting Polymer 1.0

**Comment by sarendipitee** [comment]
Pretty sure I published this to npm a while ago.

`npm show`

```
  time:
   { modified: '2016-01-28T03:27:46.821Z',
     created: '2015-01-10T00:50:20.197Z',
     '0.1.0': '2015-01-10T00:50:20.197Z',
     '0.1.1': '2015-01-13T21:23:53.355Z',
     '0.2.0': '2015-01-14T00:28:40.513Z',
     '0.3.0': '2015-02-02T23:38:36.009Z',
     '1.0.0': '2016-01-28T03:27:46.821Z' },
```

And 1.0.0 contains your PR changes, no?

**Pull request merged**
